name: Scheduled Python Script

on:
  schedule:
    - cron: "55 3 * * 1-5"   # 9:25 AM IST
    - cron: "15 13 * * 1-5"  # 6:45 PM IST

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Python script
        run: python hrone.py
